### ISSUE TITLE
algorithm, plane keywords in lineprofile in gettingstarted file

### ISSUE THREAD

**Issue by ben1sheff** [astro-group-bristol/Gradus.jl#184]
#183 seems to have fixed most issues with the gettingstarted doc, however the line profile example still has an error "Unrecognized keyword arguments: [:algorithm, :plane]" for solve. 
Removing these from the keyword args passed leads to a failure to converge (returned error: Roots.ConvergenceFailed("Algorithm failed to converge") )

**Comment by fjebaker** [comment]
That's absolutely mea culpa, I only changed half of the line in #183. It should be `method = BinningMethod()` and not `algorithm = BinningMethod()`. 

Leaving it out will cause the lineprofiles function to try to use the transfer function method, but that requires certain pre-conditions about the geometry of the disc which are difficult to infer automatically, which is why it fails to converge.

I will update this immediately as well. Thanks so much for finding these!

**Comment by fjebaker** [comment]
Fixed in https://github.com/astro-group-bristol/Gradus.jl/commit/73313153a6a1d1849c495560cb77bbf46d492b79

**Comment by ben1sheff** [comment]
Thanks so much for the prompt responses and fixes!
